// ============================================================
// MOCK DATA — acts as our "database" (replaces JSON Server)
// In a real app this would come from a database or external API
// ============================================================

import { Property } from '@/types/property';

export const properties: Property[] = [
  // ── RENTALS ──────────────────────────────────────────────
  {
    id: 'r1',
    title: 'Modern Loft in Downtown Core',
    category: 'rental',
    price: 2800,
    priceUnit: '/month',
    location: 'Downtown, New York',
    city: 'New York',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 750,
    rating: 4.7,
    reviews: 134,
    description:
      'A stunning open-plan loft in the heart of Manhattan. Floor-to-ceiling windows flood the space with natural light. Steps from Whole Foods, top restaurants, and the subway.',
    amenities: ['WiFi', 'Gym', 'Rooftop', 'Doorman', 'In-unit Laundry', 'Dishwasher'],
    featured: true,
  },
  {
    id: 'r2',
    title: 'Charming Brownstone Apartment',
    category: 'rental',
    price: 3400,
    priceUnit: '/month',
    location: 'Brooklyn, New York',
    city: 'New York',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80',
    ],
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    rating: 4.5,
    reviews: 89,
    description:
      'Classic Brooklyn brownstone with original hardwood floors, exposed brick, and a private garden. Located in the coveted Park Slope neighbourhood.',
    amenities: ['Private Garden', 'Pet Friendly', 'Storage', 'Bike Room'],
    featured: false,
  },
  {
    id: 'r3',
    title: 'Beachfront Studio — Santa Monica',
    category: 'rental',
    price: 4200,
    priceUnit: '/month',
    location: 'Santa Monica, LA',
    city: 'Los Angeles',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    ],
    bedrooms: 0,
    bathrooms: 1,
    area: 520,
    rating: 4.9,
    reviews: 211,
    description:
      'Wake up to ocean views every single day. This fully-furnished studio sits directly on the beach with a private terrace and is walking distance to the pier.',
    amenities: ['Ocean View', 'Furnished', 'AC', 'Parking', 'Pool'],
    featured: true,
  },
  {
    id: 'r4',
    title: 'Spacious Family Home — Austin',
    category: 'rental',
    price: 3100,
    priceUnit: '/month',
    location: 'East Austin, TX',
    city: 'Austin',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    rating: 4.6,
    reviews: 47,
    description:
      'A gorgeous 4-bed home on a quiet tree-lined street. Large backyard with a deck, two-car garage, and within walking distance to top-rated schools.',
    amenities: ['Backyard', 'Garage', 'Pet Friendly', 'Washer/Dryer', 'Smart Home'],
    featured: false,
  },

  // ── FOR SALE ─────────────────────────────────────────────
  {
    id: 's1',
    title: 'Luxury Penthouse — Miami Beach',
    category: 'sale',
    price: 4500000,
    priceUnit: '',
    location: 'South Beach, Miami',
    city: 'Miami',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    ],
    bedrooms: 4,
    bathrooms: 5,
    area: 5200,
    rating: 5.0,
    reviews: 18,
    description:
      'The crown jewel of South Beach — a full-floor penthouse with panoramic ocean views, private rooftop pool, and chef-grade kitchen. No expense spared.',
    amenities: ['Private Pool', 'Home Theater', 'Smart Home', 'Concierge', 'Wine Cellar', '3-Car Garage'],
    featured: true,
  },
  {
    id: 's2',
    title: 'Colonial Villa — San Francisco Hills',
    category: 'sale',
    price: 2750000,
    priceUnit: '',
    location: 'Pacific Heights, SF',
    city: 'San Francisco',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
    ],
    bedrooms: 5,
    bathrooms: 4,
    area: 4100,
    rating: 4.8,
    reviews: 32,
    description:
      'A majestic colonial home perched in Pacific Heights with sweeping Bay views. Original Victorian details preserved alongside a fully modernised interior.',
    amenities: ['Bay Views', 'Garden', 'Wine Room', 'Office', 'Guest Suite', 'EV Charger'],
    featured: true,
  },
  {
    id: 's3',
    title: 'Modern Townhouse — Chicago',
    category: 'sale',
    price: 875000,
    priceUnit: '',
    location: 'Lincoln Park, Chicago',
    city: 'Chicago',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    ],
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    rating: 4.4,
    reviews: 56,
    description:
      'Sleek new-construction townhouse in Lincoln Park. Three levels of contemporary living with a private rooftop deck overlooking the Chicago skyline.',
    amenities: ['Rooftop Deck', 'Heated Floors', 'Two-Car Garage', 'Smart Home'],
    featured: false,
  },
  {
    id: 's4',
    title: 'Countryside Estate — Nashville',
    category: 'sale',
    price: 1250000,
    priceUnit: '',
    location: 'Brentwood, Nashville',
    city: 'Nashville',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
    ],
    bedrooms: 6,
    bathrooms: 5,
    area: 6800,
    rating: 4.7,
    reviews: 23,
    description:
      'A sprawling Tennessee estate on 4 acres. Gated community, pool, tennis court, and guest cottage. The ultimate in privacy and Southern living.',
    amenities: ['Pool', 'Tennis Court', 'Guest Cottage', '4 Acres', 'Gated', 'Barn'],
    featured: false,
  },
  {
    id: 's5',
    title: 'Architect-Designed Desert Home',
    category: 'sale',
    price: 1890000,
    priceUnit: '',
    location: 'Scottsdale, Arizona',
    city: 'Scottsdale',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
    ],
    bedrooms: 4,
    bathrooms: 4,
    area: 4200,
    rating: 4.9,
    reviews: 41,
    description:
      'An award-winning desert modern masterpiece by a renowned architect. Cantilevered over a rocky ridge with jaw-dropping mountain and sunset views.',
    amenities: ['Infinity Pool', 'Mountain Views', 'Home Theater', 'Outdoor Kitchen', 'Solar Panels'],
    featured: true,
  },

  // ── HOTELS ───────────────────────────────────────────────
  {
    id: 'h1',
    title: 'The Grand Meridian Hotel',
    category: 'hotel',
    price: 420,
    priceUnit: '/night',
    location: 'Midtown, New York',
    city: 'New York',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 450,
    rating: 4.8,
    reviews: 1842,
    description:
      'A legendary New York institution reimagined for the modern traveller. Iconic art-deco lobby, Michelin-starred restaurant, and the rooftop bar voted #1 in Manhattan.',
    amenities: ['Spa', 'Fine Dining', 'Rooftop Bar', 'Concierge', 'Valet', 'Business Centre'],
    featured: true,
  },
  {
    id: 'h2',
    title: 'Boutique Ocean Hotel',
    category: 'hotel',
    price: 285,
    priceUnit: '/night',
    location: 'Malibu, California',
    city: 'Malibu',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 380,
    rating: 4.6,
    reviews: 673,
    description:
      'Perched on a cliff above the Pacific, this intimate 28-room boutique hotel offers an unmatched connection to the ocean. Every room has a sea-view balcony.',
    amenities: ['Ocean View', 'Private Beach', 'Yoga', 'Farm-to-Table Restaurant', 'Spa'],
    featured: false,
  },
  {
    id: 'h3',
    title: 'The Roosevelt Chicago',
    category: 'hotel',
    price: 210,
    priceUnit: '/night',
    location: 'The Loop, Chicago',
    city: 'Chicago',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 350,
    rating: 4.4,
    reviews: 2104,
    description:
      'Steps from Millennium Park and the Art Institute, the Roosevelt is Chicago\'s most convenient luxury address. Stunning lake views from the upper floors.',
    amenities: ['Gym', 'Pool', 'Bar', 'Pet Friendly', 'Airport Shuttle', 'Valet'],
    featured: false,
  },
  {
    id: 'h4',
    title: 'Kimpton Heritage — Austin',
    category: 'hotel',
    price: 190,
    priceUnit: '/night',
    location: '6th Street, Austin',
    city: 'Austin',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 320,
    rating: 4.5,
    reviews: 891,
    description:
      'A converted 1920s warehouse turned design-forward hotel. Pet-friendly, locally inspired decor, and right in the heart of Austin\'s vibrant entertainment district.',
    amenities: ['Rooftop Pool', 'Live Music', 'Pet Friendly', 'Bike Rental', 'Mini Bar'],
    featured: true,
  },
  {
    id: 'h5',
    title: 'Ace Hotel — Los Angeles',
    category: 'hotel',
    price: 250,
    priceUnit: '/night',
    location: 'Downtown, Los Angeles',
    city: 'Los Angeles',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 360,
    rating: 4.3,
    reviews: 1345,
    description:
      'The creative community\'s go-to LA haunt. Rooftop pool with city views, a legendary bar scene, and interiors curated by top local artists.',
    amenities: ['Rooftop Pool', 'Gym', 'Bar', 'Restaurant', 'Record Player in Rooms'],
    featured: false,
  },

  // ── RESORTS ──────────────────────────────────────────────
  {
    id: 'rv1',
    title: 'Bora Bora Overwater Bungalows',
    category: 'resort',
    price: 1850,
    priceUnit: '/night',
    location: 'Bora Bora, French Polynesia',
    city: 'Bora Bora',
    country: 'French Polynesia',
    image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
      'https://images.unsplash.com/photo-1439066290691-a2aa5ce61ac7?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    rating: 5.0,
    reviews: 2456,
    description:
      'The definitive bucket-list resort. Private overwater bungalows perched above crystal-clear lagoons with direct water access, glass-floor panels, and a slide into the sea.',
    amenities: ['Private Lagoon', 'Overwater Spa', 'Dive Centre', 'Butler Service', 'Water Sports', 'Private Beach'],
    featured: true,
  },
  {
    id: 'rv2',
    title: 'Amanjiwo Java — Borobudur',
    category: 'resort',
    price: 1200,
    priceUnit: '/night',
    location: 'Central Java, Indonesia',
    city: 'Borobudur',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 2,
    area: 1200,
    rating: 4.9,
    reviews: 876,
    description:
      'Nestled beside the ancient Borobudur temple, Amanjiwo is a sanctuary of silence and beauty. Circular suites open to jungle views and the distant volcanoes.',
    amenities: ['Infinity Pool', 'Jungle Spa', 'Cultural Tours', 'Meditation Pavilion', 'Private Butler'],
    featured: true,
  },
  {
    id: 'rv3',
    title: 'Maldives Private Island Resort',
    category: 'resort',
    price: 3200,
    priceUnit: '/night',
    location: 'North Malé Atoll, Maldives',
    city: 'Malé',
    country: 'Maldives',
    image: 'https://images.unsplash.com/photo-1439066290691-a2aa5ce61ac7?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1439066290691-a2aa5ce61ac7?w=800&q=80',
    ],
    bedrooms: 2,
    bathrooms: 2,
    area: 2100,
    rating: 5.0,
    reviews: 1102,
    description:
      'The world\'s most exclusive private island experience. Just 14 villas on a pristine atoll, accessible only by seaplane. Includes all meals, drinks, and water sports.',
    amenities: ['Private Island', 'All-Inclusive', 'Seaplane Transfer', 'Dive School', 'Chef on Call', 'Spa'],
    featured: true,
  },
  {
    id: 'rv4',
    title: 'Banyan Tree — Phuket',
    category: 'resort',
    price: 650,
    priceUnit: '/night',
    location: 'Bang Tao Beach, Phuket',
    city: 'Phuket',
    country: 'Thailand',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 2,
    area: 1400,
    rating: 4.8,
    reviews: 3201,
    description:
      'An award-winning all-pool-villa resort in lush tropical gardens. Each villa has a private pool, outdoor sala, and complimentary access to the Banyan Tree Spa.',
    amenities: ['Private Pool', 'Spa', 'Cooking Class', 'Golf', 'Beach Club', 'Kids Club'],
    featured: false,
  },
  {
    id: 'rv5',
    title: 'Amangiri — Utah Canyon',
    category: 'resort',
    price: 2400,
    priceUnit: '/night',
    location: 'Canyon Point, Utah',
    city: 'Canyon Point',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 1100,
    rating: 4.9,
    reviews: 542,
    description:
      'Carved into a remote Utah mesa, Amangiri is pure architectural poetry meeting untouched desert wilderness. The floating pool pavilion is unlike anything on earth.',
    amenities: ['Desert Spa', 'Heli-Tour', 'Rock Climbing', 'Pool Pavilion', 'Stargazing', 'Hot Air Balloon'],
    featured: true,
  },
  {
    id: 'rv6',
    title: 'Six Senses Douro Valley',
    category: 'resort',
    price: 780,
    priceUnit: '/night',
    location: 'Douro Valley, Portugal',
    city: 'Peso da Régua',
    country: 'Portugal',
    image: 'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=800&q=80',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    rating: 4.8,
    reviews: 734,
    description:
      'A 19th-century manor converted into a wellness escape amid terraced vineyards. Wine tastings, riverside kayaking, and world-class spa treatments.',
    amenities: ['Wine Tours', 'Kayaking', 'Farm-to-Table', 'Infinity Pool', 'Spa', 'Cooking Class'],
    featured: false,
  },
];

// ── Helper: format price for display ──────────────────────
export function formatPrice(property: Property): string {
  const { price, priceUnit, category } = property;
  if (category === 'sale') {
    if (price >= 1_000_000) return `$${(price / 1_000_000).toFixed(2)}M`;
    return `$${price.toLocaleString()}`;
  }
  return `$${price.toLocaleString()}${priceUnit}`;
}
